MySQL:
  ip: remotemysql.com
  port: 3306
  database: Xr4jG9xBB7
  username: Xr4jG9xBB7
  password: fQKKM0WZKB
  safeSave: true

messages:
  sucessfullCreatePattern: '&7Pomysnie utworzyles wzor o nazwie &c{PATTERNNANME}'
  sucessfullCreateBuilding: '&7Pomysnie utworzyles arene do budowania &c{NAME} &7o wzorze &c{PATTERNNAME}'
  moneyAddMessage: 'Otrzymales {MONEY} twoj stan konta {BALANCE}'